### ISSUE TITLE
Allow users to specify alternative data layer names.

### ISSUE THREAD

**Issue by philpott** [Mikeulrich75/dataLayerBuilderStandardEcommerce#1]
Since the data layer can be [renamed](https://developers.google.com/tag-manager/devguide#renaming) it would be nice to allow users to specify an alternative name.

**Comment by Mikeulrich75** [comment]
This same question was asked and addressed for my other custom template 'dataLayer Builder + Standard Ecommerce' here https://github.com/Mikeulrich75/dataLayerBuilderEnhancedEcommerce/issues/1#issuecomment-546088885. 

I am closing this issue b/c this request isn't possible as the permissions are manually set.
